#pragma once

#define LANGUAGE_CATEGORY(F)\
  F(No_Category,=0)\
  F(General,)\
  F(Option_UI,)\
  F(Example_Message_UI,)\
  F(Message,)\
  F(Scroll_Area_Option_UI,)\
  F(Receiver_Option_UI,)\
  F(Skill_Filter_Option_UI,)\
  F(Skill_Icons_Option_UI,)\
  F(Profile_Option_UI,)\
  F(Message_General,)\
  F(Message_Category_Player_Out,)\
  F(Message_Category_Player_In,)\
  F(Message_Category_Pet_Out,)\
  F(Message_Category_Pet_In,)\
  F(Message_Type_Physical,)\
  F(Message_Type_Crit,)\
  F(Message_Type_Bleeding,)\
  F(Message_Type_Burning,)\
  F(Message_Type_Poison,)\
  F(Message_Type_Confusion,)\
  F(Message_Type_Retaliation,)\
  F(Message_Type_Torment,)\
  F(Message_Type_DoT,)\
  F(Message_Type_Heal,)\
  F(Message_Type_HoT,)\
  F(Message_Type_Shield_Got,)\
  F(Message_Type_Shield,)\
  F(Message_Type_Block,)\
  F(Message_Type_Evade,)\
  F(Message_Type_Invulnerable,)\
  F(Message_Type_Miss,)\
  F(Message_Player_Out_Physical,)\
  F(Message_Player_Out_Crit,)\
  F(Message_Player_Out_Bleeding,)\
  F(Message_Player_Out_Burning,)\
  F(Message_Player_Out_Poison,)\
  F(Message_Player_Out_Confusion,)\
  F(Message_Player_Out_Retaliation,)\
  F(Message_Player_Out_Torment,)\
  F(Message_Player_Out_DoT,)\
  F(Message_Player_Out_Heal,)\
  F(Message_Player_Out_HoT,)\
  F(Message_Player_Out_Shield_Got,)\
  F(Message_Player_Out_Shield,)\
  F(Message_Player_Out_Block,)\
  F(Message_Player_Out_Evade,)\
  F(Message_Player_Out_Invulnerable,)\
  F(Message_Player_Out_Miss,)\
  F(Message_Player_In_Physical,)\
  F(Message_Player_In_Crit,)\
  F(Message_Player_In_Bleeding,)\
  F(Message_Player_In_Burning,)\
  F(Message_Player_In_Poison,)\
  F(Message_Player_In_Confusion,)\
  F(Message_Player_In_Retaliation,)\
  F(Message_Player_In_Torment,)\
  F(Message_Player_In_DoT,)\
  F(Message_Player_In_Heal,)\
  F(Message_Player_In_HoT,)\
  F(Message_Player_In_Shield_Got,)\
  F(Message_Player_In_Shield,)\
  F(Message_Player_In_Block,)\
  F(Message_Player_In_Evade,)\
  F(Message_Player_In_Invulnerable,)\
  F(Message_Player_In_Miss,)\
  F(Message_Pet_Out_Physical,)\
  F(Message_Pet_Out_Crit,)\
  F(Message_Pet_Out_Bleeding,)\
  F(Message_Pet_Out_Burning,)\
  F(Message_Pet_Out_Poison,)\
  F(Message_Pet_Out_Confusion,)\
  F(Message_Pet_Out_Retaliation,)\
  F(Message_Pet_Out_Torment,)\
  F(Message_Pet_Out_DoT,)\
  F(Message_Pet_Out_Heal,)\
  F(Message_Pet_Out_HoT,)\
  F(Message_Pet_Out_Shield_Got,)\
  F(Message_Pet_Out_Shield,)\
  F(Message_Pet_Out_Block,)\
  F(Message_Pet_Out_Evade,)\
  F(Message_Pet_Out_Invulnerable,)\
  F(Message_Pet_Out_Miss,)\
  F(Message_Pet_In_Physical,)\
  F(Message_Pet_In_Crit,)\
  F(Message_Pet_In_Bleeding,)\
  F(Message_Pet_In_Burning,)\
  F(Message_Pet_In_Poison,)\
  F(Message_Pet_In_Confusion,)\
  F(Message_Pet_In_Retaliation,)\
  F(Message_Pet_In_Torment,)\
  F(Message_Pet_In_DoT,)\
  F(Message_Pet_In_Heal,)\
  F(Message_Pet_In_HoT,)\
  F(Message_Pet_In_Shield_Got,)\
  F(Message_Pet_In_Shield,)\
  F(Message_Pet_In_Block,)\
  F(Message_Pet_In_Evade,)\
  F(Message_Pet_In_Invulnerable,)\
  F(Message_Pet_In_Miss,)

#define LANGUAGE_KEY(F)\
  F(No_Key,=0)\
  F(Outdated_Popup_Title,)\
  F(Outdated_Popup_Content,)\
  F(Outdated_Popup_Found_Version,)\
  F(Outdated_Popup_Required_Version,)\
  F(Outdated_Popup_Confirmation,)\
  F(Font,)\
  F(Font_Size,)\
  F(Font_Size_Type,)\
  F(Default_Font_Size,)\
  F(Default_Crit_Font_Size,)\
  F(Custom_Font_Size,)\
  F(Skill_Filter_Type_ID,)\
  F(Skill_Filter_Type_Name,)\
  F(Font_Master,)\
  F(Font_Default,)\
  F(Text_Align_Left,)\
  F(Text_Align_Center,)\
  F(Text_Align_Right,)\
  F(Text_Curve_Left,)\
  F(Text_Curve_Straight,)\
  F(Text_Curve_Right,)\
  F(Old_Save_Popup_Title,)\
  F(Old_Save_Popup_Content,)\
  F(Old_Save_Popup_Backup_Made,)\
  F(Old_Save_Popup_Confirmation,)\
  F(Unknown_Skill_Source,)\
  F(Unknown_Skill_Target,)\
  F(Unknown_Skill_Name,)\
  F(Default_Scroll_Area_Incoming,)\
  F(Default_Scroll_Area_Outgoing,)\
  F(Title,)\
  F(Menu_Bar_General,)\
  F(Menu_Bar_Scroll_Areas,)\
  F(Menu_Bar_Profession_Colors,)\
  F(Menu_Bar_Filtered_Skills,)\
  F(Menu_Bar_Skill_Icons,)\
  F(Menu_Bar_Profiles,)\
  F(General_Enabled,)\
  F(General_Scrolling_Speed,)\
  F(General_Scrolling_Speed_Toolip,)\
  F(General_Drop_Shadow,)\
  F(General_Max_Messages,)\
  F(General_Max_Messages_Toolip,)\
  F(General_Combine_Messages,)\
  F(General_Combine_Messages_Toolip,)\
  F(General_Self_Only_As_Incoming,)\
  F(General_Self_Only_As_Incoming_Toolip,)\
  F(General_Out_Only_For_Target,)\
  F(General_Out_Only_For_Target_Toolip,)\
  F(Scroll_Areas_New,)\
  F(Scroll_Areas_Name,)\
  F(Receiver_Name,) \
  F(Messages_Category,)\
  F(Messages_Category_Player_Out,)\
  F(Messages_Category_Player_In,)\
  F(Messages_Category_Pet_Out,)\
  F(Messages_Category_Pet_In,)\
  F(Messages_Type,)\
  F(Messages_Type_Physical,)\
  F(Messages_Type_Crit,)\
  F(Messages_Type_Bleeding,)\
  F(Messages_Type_Burning,)\
  F(Messages_Type_Poison,)\
  F(Messages_Type_Confusion,)\
  F(Messages_Type_Retaliation,)\
  F(Messages_Type_Torment,)\
  F(Messages_Type_Dot,)\
  F(Messages_Type_Heal,)\
  F(Messages_Type_Hot,)\
  F(Messages_Type_Shield_Receive,)\
  F(Messages_Type_Shield_Remove,)\
  F(Messages_Type_Block,)\
  F(Messages_Type_Evade,)\
  F(Messages_Type_Invulnerable,)\
  F(Messages_Type_Miss,)\
  F(Profession_Colors_Guardian,)\
  F(Profession_Colors_Warrior,)\
  F(Profession_Colors_Engineer,)\
  F(Profession_Colors_Ranger,)\
  F(Profession_Colors_Thief,)\
  F(Profession_Colors_Elementalist,)\
  F(Profession_Colors_Mesmer,)\
  F(Profession_Colors_Necromancer,)\
  F(Profession_Colors_Revenant,)\
  F(Profession_Colors_Undetectable,)\
  F(Skill_Icons_Warning,)\
  F(Skill_Icons_Enable,)\
  F(Skill_Icons_Preload_Description,)\
  F(Skill_Icons_Preload,)\
  F(Skill_Icons_Display_Type,)\
  F(Skill_Icons_Display_Type_Normal,)\
  F(Skill_Icons_Display_Type_Black_Culled,)\
  F(Skill_Icons_Display_Type_Black_Border_Culled,)\
  F(Skill_Icons_Display_Type_Black_Border_Touching_Culled,)\
  F(Multiple_Sources,)\
  F(Number_Of_Hits,)\
  F(Horizontal_Offset,)\
  F(Vertical_Offset,)\
  F(Width,)\
  F(Height,)\
  F(Text_Align,)\
  F(Text_Flow,)\
  F(All_Receivers,)\
  F(New_Receiver,)\
  F(Template,)\
  F(Available_Parameters,)\
  F(Delete_Confirmation_Title,)\
  F(Delete_Confirmation_Content,)\
  F(Delete_Confirmation_Confirmation,)\
  F(Delete_Confirmation_Cancel,)\
  F(Parameter_Description_v,)\
  F(Parameter_Description_n,)\
  F(Parameter_Description_s,)\
  F(Parameter_Description_p,)\
  F(Parameter_Description_c,)\
  F(Parameter_Description_r,)\
  F(Parameter_Description_i,)\
  F(Default_Value,)\
  F(Filter_By,)\
  F(Profile_Description,)\
  F(Master_Profile,)\
  F(Character_Specific_Profile_Heading,)\
  F(Character_Specific_Profile_Enabled,)\
  F(Current_Profile_Heading,)\
  F(Current_Profile_Name,)\
  F(Create_Profile_Copy,)\
  F(Delete_Profile,)\
  F(Profile_Copy_Suffix,)\
  F(Start_Recording,)\
  F(Stop_Recording,)\
  F(Start_Emitting,)\
  F(Stop_Emitting,)\
  F(Clear_Recorded_Messages,)
